### ISSUE TITLE
コードが動きません。

### ISSUE THREAD

**Issue by shohei-matsushita** [harukaxq/langchain-book#1]
[04_memory/chat_memory_1.py](https://github.com/harukaxq/langchain-book/blob/master/04_memory/chat_memory_1.py) をWindows環境で起動すると、最初の入力で以下のエラーが出てしまいます。対処法をご教授ください。

1 validation error for HumanMessage
content
str type expected (type=type_error.str)

**Comment by shohei-matsushita** [comment]
申し訳ありません。思わず投稿してしまいましたが、こちら公式リポジトリではないですよね。

**Comment by harukaxq** [comment]
@shohei-matsushita 
こちら動作確認したところ、chainlitに破壊的なアップデートが入り記載のソースコードだと動作しなくなる問題がありました。
申し訳有りません。

以下コマンドを実行して、chainlitのバージョンを執筆当時のものに下げてみてください。

```
python3 -m pip install chainlit==0.5.1
```

報告ありがとうございました！
