### ISSUE TITLE
06_agent/agent_5.py で2回目の実行結果が正しく表示されません

### ISSUE THREAD

**Issue by shu-kob** [harukaxq/langchain-book#3]
お世話になっております。
06_agent/agent_5.py 「文脈に応じた返答ができるAgentを作成する」で、
1回目の実行結果はちゃんとスコッチウィスキーの内容を返答するのですが、
2回目の実行結果が「2回目の実行結果: 以前の指示をもう一度実行してください。」と
質問文をそのまま返すのみとなります。

Python Versionは3.11.8で、
Readmeの`python3 -m pip install -r requirements.txt`も実行しました。

2回目の実行結果がただ単に質問文をそのまま返すだけなのはなぜでしょうか？

**Comment by harukaxq** [comment]
issueありがとうございます。
確認しますね！

**Comment by shu-kob** [comment]
ありがとうございます。
よろしくお願いいたします。

**Comment by harukaxq** [comment]
遅れてしまい申し訳ありません。こちら確認しました。
OpenAI側でモデルが更新されて、動作が変わってしまっていました。
gpt-3.5-turboはAgentとして使用すると稀に命令を無視してしまう問題があり、モデル更新が原因で以前とは異なる動きになり今回の問題が発生したようです。
執筆当初はgpt-4を使うには申請が必要だった都合上gpt-3.5-turboでのサンプルコードとなっていますが、現在はgpt-4が全員に開放されているので結論、以下のように使用するモデルをgpt-4に変更していただければ問題ありません。

`chat = ChatOpenAI(
    temperature=0,
    model="gpt-3.5-turbo"
)`
↓
`chat = ChatOpenAI(
    temperature=0,
    model="gpt-4"
)`

**Comment by shu-kob** [comment]
gpt-4に切り替えたら2回目も1回目と同じ質問をして実行結果も期待通りのものとなりました。
調査いただきありがとうございました。
クローズします。
